"""JNTUK affiliated-college names keyed by hall-ticket college code."""

college_details = {
    '2A': 'Satya Institute Of Management Studies, Nugondapalli',
    '2B': 'PNC & Vijai Institute of Engineering & Technology, Pirangipuram',
    '2C': 'Kamala Institute Of Management Studies, Markapur',
    '2K': 'Benaiah Institute Of Technology & Science, Burugupudi',
    '2L': 'D N R School Of Business Management, Bhimavaram',
    '2N': 'Chaitanya Institute Of Computer Science, Kakinada',
    '2R': 'Nalanda Institute Of P.g. Studies, Kantepudi',
    '2T': 'Malineni Lakshmaiah Mba College, Kanumalla',
    '2W': 'G V R & S College Of Engineering & Technology,guntur',
    '2X': 'Hindu College Of Engineering & Technology, Guntur',
    '2Y': 'Krishna Chaitanya Institute Of Management, Devarajugattu',
    '2Z': 'Indo American Institutions - Technical Campus, Anakapalli',
    '3B': 'VSM College of Engineering, Ramachandra Puram',
    '3C': 'D M S S V Hindu College Of Engineering, Machilipatnam.',
    '3E': 'Chirla College Of P.g. Studies, Chirala',
    '3F': 'Abinav Institute Of Management & Technology, Singarayakonda.',
    '3G': 'Aditya Pharmacy College, Surampalem',
    '3H': 'Aditya College Of Pharmacy, Surampalem',
    '3J': 'Raghu Institute Of Technology, Dakammari, Bheemunipatnam Mandal, Visakhapatnam District',
    '3M': 'Koringa College Of Pharmacy, Korangi',
    '6B': 'Swami Vivekananda Engineering College, Bobbili',
    '6C': 'Miracle Educational Society Group Of Institutions, Bhogapuram',
    '6D': 'Sanketika Inst Of Tech & Management,visakhapatnam',
    '6E': 'Gonna Institute Of Information Technology & Science, Aganampudi',
    '6F': 'Sai Ganapathi Engineering College, Anandapuram',
    '6G': 'Visakha Techinacl Campus, Narava',
    '6H': 'Sri Chaitanya Engineering College, Madhurawada',
    '6J': 'Simhadhri Educational Socity Group Of Inst, Sabbavaram',
    '6K': 'Ideal Institute Of Technology, Kakinada',
    '6L': 'Amalapuram Institute Of Management Science & College Of Engineering',
    '6M': 'BVC College of Engineering, Rajanagaram',
    '6N': 'Srinivasa Institute Of Engineering & Technology, Amalapuram',
    '6P': 'Prasiddha College Of Engineering & Technology, Amalapuram',
    '6Q': 'Kakinada Institute of Engineering and Technology - II, Korangi',
    '6R': 'GIET College of Engineering, Rajahmundry',
    '6T': 'Pydah College Of Engineering, Matlapalem',
    '6W': 'International School Of Technology & Science For Women , Rajanagaram',
    '7A': 'Gayatri Institute Of Engineering & Technology, Jangareddygudem',
    '7D': 'Chaitanya Engineering College, Bhimavaram',
    '7E': 'Helapuri Institute Of Technology & Science, Vegavaram',
    '7G': 'Muttamsetty Venkata Narayana Institute Of Management Studies & Research, Eluru',
    '7H': 'Green Royal Acadamy Of Pharmaceutical Education & Science,koyyalagudem',
    '7J': 'Sri Vani Group Of Institutions,chevuturu',
    '7K': 'D J R College Of Engineering & Technology,vijayawada',
    '7N': 'Vijaya Institute Of Pharmaceutical Science For Women,enikepadu',
    '7P': 'Global Institute Of Management & Technology,bommuluru',
    '7Q': 'Vijaya Institute Of Management Science For Women , Enikepadu',
    '7R': 'Chintalapudi Engineering College, Chintalapudi',
    '7T': 'Nannapaneni Venkata Rao College Of Engineering & Technology,tenali',
    '7W': 'Malineni Perumallu Educational Society’s Group Of Inatiuttions',
    '7Y': 'A1 Global Institute Of Engineering & Technology,markapur',
    '7Z': 'Indira Institute Of Technology & Science,markapur',
    '8A': 'Rise Krishna Sai Prakasam Group of Institutions, Vallur',
    '8B': 'Rise Krishna Sai Gandhi Group of Institutions, Vallur',
    '8C': 'Chaitanya College Of Pharmacy,devarajugattu',
    '8D': 'Addanki Institute Of Management & Sciences, Addanki',
    '8F': 'Saradha Institute Of Technology & Management, Vijayawada',
    '8H': 'MVR College of Engineering & Technology, Paritala',
    '8K': 'Gokul Group Of Institutions, Bobbili',
    '8M': 'Visakha Institute Of Management Science, Bheemili',
    '8N': 'AKRG College of Pharmacy, Nallajerla',
    '8Q': 'St.mary’s Colleges Of B Pharmacy,surampalem',
    '8R': 'Ba&kr Mca College, Ongole',
    '8T': 'Dhanekula Institute Of Engineering & Technology, Ganguru, Vijayawada',
    '8W': 'Velagapudi Rama Krishna Siddhartha Engineering College, Vijayawada',
    '8X': 'Kallam Harinatha Reddy Institute Of Technology, Chowdavaram, Guntur',
    '8Y': 'Vikas College Of Pharmacy,visanna Peta',
    '8Z': 'Rajiv Gandhi Institute Of Management & Science, Atchampeta',
    '9A': 'Nimra College Of Pharmacy, Ibrahimpatnam',
    '9B': 'Global Institute Of Business Management, Markapur',
    '9D': 'Gonna Institute Of Technology & Management, Aganampudi',
    '9E': 'NRI College of Pharmacy, Pothavarapupadu',
    '9F': 'Nova Institute Of Technology, Eluru',
    '9G': 'Montessori Siva Sivani College Of Pharmacy, Myalavaram',
    '9H': 'Newton’s Institute Of Science & Technology, Macherla',
    '9K': 'Sankar Reddy Institute Of Pharmaceutical Sciences,bestavaripeta',
    '9L': 'Nimra College Of Business Management, Ibrahimpatnam',
    '9M': 'Sri Sai Madhavi Institute Of Engineering & Technology, Mallampudi',
    '9N': 'Nova Pg College(mca),jupudi Village',
    '9P': 'DNR College of Engineering & Technology, Bhimavaram',
    '9Q': 'Nova Pg College(mba),jupudi Village',
    '9T': 'Vikas Group Of Institutions, Vissannapet',
    '9U': 'Vishwa Bharathi College Of Technology & Management',
    '9V': 'Vallabhaneni Venkatadri Institute Of Pharmaceutical Science,gudlavalleru',
    '9W': 'Sri Sarathi Institute Of Engineering & Technology,nuzvid',
    '9Y': 'Nova College Of Business Management, Nuzivid',
    '9Z': 'Gayatri Group Of Institutions, Jangareddygudem',
    'A0': 'Nova College Of Engineering & Technology , Jangareddygudem',
    'A1': 'Newton’s Institute Of Engineering ,arugurajupally',
    'A2': 'Swarnandhra College Of Engineering & Technology, Narsapur',
    'A3': 'Pragathi Engineering College, Surampalem',
    'A4': 'Loyola Institute Of Technology & Management,dhulipalla',
    'A5': 'Aditya Inst Of Tech & Manag, Tekkali',
    'A6': 'Sri Prakash College Of Engineering, Tuni',
    'A7': 'Nalanda Institute Of Engineering &technology,satenapalli',
    'A8': 'Sri Vasavi Engineering College, Tadepalligudem',
    'A9': 'Aditya Engineering College, Surampalem',
    'AB': 'Vignan Pharmacy College,vadlamudi',
    'AC': 'Vignan Inst Pharmaceutical Technology, Gajuwaka',
    'AH': 'Amara Institute Of Engineering & Technology,satuluru',
    'AJ': 'Amrita Sai Institute Of Science & Technology,paritala',
    'AP': 'Bhimavaram Institute Of Engineering & Technology, Bhimavaram',
    'AR': 'Sai Tirumala Nvr Engineering College ,chebrolu',
    'B0': 'Shri Vishnu Engineering College For Women, Bhimavaram',
    'B2': 'Kakinada Institute of Engineering and Technology, Korangi',
    'B3': 'K C Reddy Pg College',
    'B4': 'ASK College of Technology & Management, Anakapally',
    'B5': 'Dr. Paul Raj Engineering College, Laxmidevipeta (v), Yatapaka (p), Nellipaka (m)',
    'B6': 'Satya Institute Of Technology & Management, Gajularega.',
    'B7': 'Emmanuel College Of Pharmacy, Singanna Banda',
    'B8': 'Sir C.r.reddy College Of Engineering, Eluru',
    'B9': 'Sagi Ramakrishnam Raju Engineering College, Chinnaamiram(post), Bhimavaram',
    'BJ': 'St.mary’s Group Of Institutions Guntur, Chebrolu',
    'BN': 'Tenali Engineering College, Anumariapudi',
    'BQ': 'Vasireddy Venkatadri Institute Of Technology,pedakakani',
    'C0': 'Maestro School Of Planning & Architecture, Vijayawada',
    'C1': 'Vaishnavi School Of Architecture & Planning Vijayawada, Vijayawada.',
    'C2': 'M.r.k. College Of Architecture, Veeravasaram, Bhimavaram',
    'C3': 'Varaha College Of Architecture & Planning, Nar Ava, Visakhapatnam',
    'C4': 'All Saints P.g.college, Singanabanda, Bheemili(m), Visakhapatnam',
    'CD': 'Narasaraopeta Institute Of Pharmaceutical Science,narasaraopet',
    'CR': 'Nalanda Institute Of Pharmaceutical Sciences,kantepudi',
    'DA': 'Sri Sivani College Of Pharmacy, Srikakulam',
    'DR': 'Nova College Of Pharmaceutical Education & Research,jupudi',
    'DU': 'St. Ann’s College Of Pharmacy,chirala',
    'E9': 'Chirala Engineering College,chirala',
    'EM': 'Swarnandhra Institute Of Engineering & Technology,narsapur',
    'F0': 'St. Ann’s College Of Engineering & Technology,vetapalem',
    'F9': 'Prakasam Engineering College,kandukur',
    'FE': 'Vignan’s Lara Institute Of Technology & Science,vadlamudi',
    'FF': 'Mandava Institute Of Engineering & Technology, Jagayyapet',
    'G5': 'Akula Sreeramulu Institute Of Engineering & Technology, Tadepalligudem',
    'G6': 'Thandrapaparaya Institute Of Science & Technology, Bobbili',
    'GC': 'Jogaiah Institute Of Technology & Science,kalagampudi',
    'GK': 'Priayadarshni Institute Of Technology & Management,vatticherukuru',
    'H4': 'BVC Institute of Technology & Science, Amalapuram',
    'H7': 'DVR Dr. Hema Sekhar MIC College of Technology,Kachakacherla',
    'H9': 'Gokul Institute Of Technology & Science,bobbili',
    'HE': 'Jogaiah Institute Of Technology & Science, Kalagampudi',
    'HH': 'Gokul Pharamacy College,bhobbili',
    'HJ': 'ABR College of Engineering & Technology , Kanigiri',
    'HK': 'AKRG College of Engineering & Technology, Nallajerla',
    'HM': 'A M Reddy Memorial College Of Engineering Technology, Narasaraopet',
    'HN': 'Adarsh College Of Engineering, Chebrolu',
    'HP': 'Andhra Loyola Institute Of Engineering & Technology, Vijayawada',
    'HQ': 'Avanthi’s Research & Technological Academy, Bhogapuram',
    'HR': 'Buchipalli Venkayamma Subbareddy Enginneering College,chimakurthy.',
    'HT': 'Chalapathi Institute Of Technology, Mothada',
    'HU': 'Chebrolu Engineering College,chebrolu',
    'JA': 'Coastal Inst Of Technology & Management, Kothavalasa',
    'JC': 'DJR Institute of Engineering & Technology,Vijayawada',
    'JD': 'Eluru College Of Engineering & Technology, Eluru',
    'JE': 'Eswar College Of Engineering, Kesanupalli',
    'JF': 'Gandhiji Institute Of Science & Technology, Gattu Bhimavaram',
    'JG': 'GVP College of Engg for Women, Madhurawada',
    'JH': 'Grandhi Varalakshmi Venkatarao Institute Of Technology, Bhimavara',
    'JK': 'Guntur Engineering College, Yanamandala',
    'JM': 'GDMM College of Engineering & Technology, Naadigama',
    'JN': 'Kakinada Institute of Engineering and Technology for Women, Korangi',
    'JP': 'Kakinada Institute Of Technoligical & Sciences, Ramchandrapuram',
    'JQ': 'Kakinada Institute Of Technology & Science, Peddapuram',
    'JR': 'KKR & KSR Institute of Technology & Science,Vinjanampudi',
    'JT': 'A S N Women’s Engineering College, Burrupalem',
    'JU': 'Krishna Chaitanya Institute Of Technology & Science,devarajugattu.',
    'K1': 'Pydah Colloege Of Engineering & Technology, Anandapuram',
    'K6': 'Sasi Institute Of Technology & Engineering, Tadepalligudem',
    'KC': 'Krishnaveni Engineering College For Women, Narasaraopet',
    'KD': 'Lendi Institute Of Engineering & Technology, Denkada',
    'KE': 'Malineni Lakshmaiah Women’s Engineering College,pulladigunta',
    'KH': 'Narasaraopeta Institute Of Technology,yallamanda',
    'KK': 'Nova College Of Engineering & Technology,ibrahimptnam',
    'KN': 'NRI Institute of Technology,Pothavarappadu',
    'KP': 'NRI institute of Technology,Guntur',
    'KQ': 'Pace Institute Of Technology & Science,vallur',
    'KR': 'Paladugu Parvathi Devi College Of Engineering & Technology, Surampalli',
    'KT': 'Potti Sreeramulu C M Rao College Of Engineering & Technology, Vijayawada',
    'KU': 'Priyadarshini Institute Of Technology & Science For Women, Chintalapudi',
    'L1': 'VRS & YRN College of Engineering & Technology,Chirala',
    'L3': 'Vignan’s Institute Of Information Technology, Gajuwaka',
    'L6': 'Chaitanya Engineering College,madhurawada',
    'MA': 'QIS Institute of Technology,Ongole',
    'MC': 'R K College Of Engineering,vijayawada',
    'MD': 'Rajamhendri Institute Of Engineering & Technology, Bhoopalapatnam',
    'ME': 'Ramachandra College Of Engineering, Eluru',
    'MF': 'Sarojini Institute Of Technology,telaprolu',
    'MG': 'Sree Vahini Institute Of Science & Technology,thiruvuru',
    'MH': 'Aditya College Of Engineering, Surampalem',
    'MK': 'Sri Mittapalli Institute Of Technology For Women,chintalapudi',
    'MM': 'Sri Sai Madhavi Institute Of Science & Technology, Mallampudi',
    'MN': 'Sri Sivani Institute Of Technology, Srikakulam',
    'MQ': 'Sri Vasavi Institute Of Engineering & Technology ,pedana',
    'MR': 'Sri Vatsavai Krishmraju College Of Engineering & Technology, Gollala Koderu',
    'MT': 'Sri Venkateswara College Of Engineering & Technology, Etcherla',
    'MU': 'Sri Venkateswara Institute Of Science & Information Technology, Nallajerla',
    'NA': 'Lingayas Institute Of Technology & Management, Mandalavari Gudem',
    'ND': 'St.mary’s Women’s Engineering College, Budampadu',
    'NE': 'Tirumala Engineering College,narasaraopet',
    'NF': 'Universal College Of Engineering & Technology,dokiparru',
    'NG': 'Usha Rama College Of Engineering & Technology ,telaprolu',
    'NH': 'VKR & VNB & AGK College of Engineering, Gudiwada',
    'NJ': 'V S Lakshmi Engineering College, Matlapalem',
    'NK': 'Velaga Nageswara Rao College Ofengineering,ponnur',
    'NM': 'Vignan’s Institute Of Engineering For Women, Gajuwaka',
    'NN': 'Vignan’s Nirula Institute Of Technology & Science For Women,palakaluru',
    'NP': 'Vijaya Institute Of Technology For Women ,enikepadu',
    'NQ': 'Vikas College Of Engineering & Technology , Nunna',
    'NR': 'Baba Institute Of Technology & Science, Madhurawada',
    'NT': 'Visakha Institute Of Enginrring & Technology,narava',
    'NU': 'Nadimpalli Satyanarayana Raju Institute Of Technology, Sontyam',
    'P3': 'Aditya College Of Engineering & Technology, Surampalem',
    'PA': 'Vishnu Institute Of Technology, Bhimavaram',
    'PC': 'Vizag Institute Of Technology, Bheemili',
    'PD': 'West Godavari Institute Of Science & Technology, Nallajerla',
    'PE': 'Adarsa College Of Pharmacy, Gokavaram',
    'PG': 'BA&KR College of Pharmacy,Ongole',
    'PH': 'Bellamkonda Institute Of Technology & Science,podili',
    'PJ': 'MRR College of Pharmacy, Nandigama',
    'PK': 'Viswanadha Inst Of Pharmaceuticel Sciences,anandapuram',
    'Q7': 'Avanthi Institute Of Engineering & Technology,bhogapuram',
    'R8': 'Sri Sunflower College Of Engineering & Technology, Lankapalli',
    'S0': 'Chaitanya Institute Of Science & Technology, Madhavaptnam',
    'T5': 'Avanthi Institute Of Phramaceutical Sciences,bhogapuram',
    'T7': 'Nova College Of Pharmacy, Jangareddygudem',
    'T9': 'GIET Engineering College',
    'U4': 'Dadi Inst Of Engg & Tech, Anakapalli',
    'U9': 'Sri Mittapalli College Of Engineering, Thummalapalem',
    'VV': 'University College Of Engineering, Vizianagaram',
    'W2': 'Kaushik College Of Engineering, Gambhiram',
    'W3': 'Nimra Institute Of Science & Technology,jupudi',
    'W6': 'Sri Sivani College Of Engineering, Srikakulam',
    'X2': 'Priyadarshini Institute Of Technology & Science, Chintalapudi',
    'X4': 'S R K Institute Of Technology,enikepadu',
    'X9': 'Sri Satyanarayana Engineering College,ongole',
    'Y3': 'QIS Collegeof Pharmacy ,Ongole',
    'Z4': 'D C R M Pharmacy College,inkollu',
    '02': 'University College of Engineering, Kakinada',
    '03': 'University College Of Engineering, Narasaraopet',
    '10': 'Bapatla College Of Pharmacy, Bapatla',
    '13': 'Gayathri Vidya Parishad College Of Engineering,madhurawada',
    '22': 'BVC Engineering College, Odalarevu',
    '23': 'Nimra College Of Engineering & Technology, Imbrahimpatnam',
    '33': 'MVGR College of Engineering, Chinthalavalasa.',
    '34': 'GMR Institute of Technology,Rajam',
    '35': 'Dr.samuel George Institute Of Engineering & Technology, Markapur',
    '43': 'Vishwa Bharathi College Of Pharmaceutical Science,perecherla',
    '47': 'Narasaraopeta Engineering College, Yellamanda',
    '48': 'Gudlavalleru Engineering College, Gudlavalleru',
    '49': 'QIS College of Engineering & Technology,Ongole',
    '50': 'Prasad V Potluri Siddhartha Institute Technology,kanuru',
    '51': 'Sarada Inst Of Sc Tech & Manag, Srikakulam',
    '52': 'Viswanadha Inst Of Tech & Management, Anandapuram',
    '53': 'Akula Sreeramulu College Of Engineering, Tanuku',
    '54': 'Sri Sarathi Institute Of Engineering & Technology,nuzvid',
    '55': 'Godavari Inst of Engg & Tech, Rajahmundry',
    '76': 'Lakkireddy Balireddy College Of Engineering, Mylavaram',
    '77': 'Rao & Naidu Engineering College,ongole',
    '81': 'Avanthi Inst Of Engineering & Technology,narsipatnam',
    '85': 'Malineni Lakshmaiah Engineering College,singarayakonda',
    '90': 'Sri Chundi Ranganayakulu Engineering College, Ganapavaram',
    '96': 'Lenora College Of Engineering, Rampachodavaram',
    '98': 'Raghu Engineering College, Bheemili',
    '99': 'Avanthi’s St. Theressa Institute Of Engineering & Technology, Garividi',
}


def get_college_name(roll_number: str) -> str:
    """Return the official college name encoded in a JNTUK hall ticket."""
    if not roll_number or len(roll_number) < 4:
        return "Unknown"
    return college_details.get(roll_number[2:4].upper(), "Unknown")
